repos:
  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.30.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs_replace
        args: ['--with-aggregate-type-defaults', '--dest=docs/terraform.md']
  - repo: local
    hooks:
        - id: build-readme
          name: Build README.md
          language: system
          entry: make readme/sync
          types: [file]
          files: ^README\.yaml$
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-merge-conflict

